name: vql-build
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'
          
      - name: Build front-end project
        run: |
          npm install
          npm run build
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vql-dist
          path: |
            dist
            Dockerfile
            nginx.conf
          retention-days: 1
    
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Download archived artifacts
        uses: actions/download-artifact@v2
        with:
          name: vql-dist
      
      - name: Build into docker and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: vql:latest
    
